imports:
    - { resource: services.yml }
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    aws_s3_region: eu-west-1

framework:
    #esi:             ~
    # translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    # form:            ~
    # csrf_protection: ~
    # validation:      { enable_annotations: false }
    #serializer:      { enable_annotations: true }
    # templating:
    #     engines: ['twig']
    # default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    # session:
    #     # handler_id set to null will use default session handler from php.ini
    #     handler_id:  session.handler.native_file
    #     save_path:   "%kernel.root_dir%/../tmp/sessions/%kernel.environment%"
    # fragments:       ~
    http_method_override: false
    # assets: ~
    php_errors:
        log: true
    cache:
        pools:
            cache.programmes:
                # cache.adapter.psr6 act as a proxy for the adapter we set on the "provider" section,
                # this is required when and adapter is not supported directly
                adapter: cache.adapter.psr6
                provider: cache.null_provider # locally we don't want to use cache

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: "%database_server_version%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #     path:     "%database_path%"
        types:
            date_partial: BBC\ProgrammesPagesService\Data\ProgrammesDb\Type\DatePartialType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    ProgrammesPagesService:
                        type: annotation
                        dir: "%kernel.root_dir%/../vendor/bbc/programmes-pages-service/src/Data/ProgrammesDb/Entity"
                        is_bundle: false
                        prefix: BBC\ProgrammesPagesService\Data\ProgrammesDb\Entity
                filters:
                    embargoed_filter:
                        class: BBC\ProgrammesPagesService\Data\ProgrammesDb\Filter\EmbargoedFilter
                        enabled: true
                dql:
                    string_functions:
                        MATCH_AGAINST: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\MatchAgainst
                        GROUP_CONCAT: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\GroupConcat
                    datetime_functions:
                        YEAR: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Year
                        MONTH: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Month
                        DAY: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Day

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            timestampable: true
