#!/bin/sh

set -e
RESULT=0

export SYMFONY_ENV=prod;
# Download and run composer
if [ ! -f "composer.phar" ]; then
    curl -sS https://getcomposer.org/installer | php
fi
if [ -n "$OAUTH" ]; then
    php composer.phar config -g github-oauth.github.com $OAUTH
fi
# Make sure the reports directory exists
if [ ! -d "build/reports" ]; then
    mkdir -p build/reports
fi

if [ "$RESULT" = "0" ]; then
    php composer.phar --no-ansi --no-interaction --no-dev --optimize-autoloader --prefer-dist install || RESULT=1
fi

exit $RESULT
