#!/bin/sh
function docker_run {
    docker run --rm \
    -u `id -u`:`id -g` \
    -e OAUTH="$OAUTH_TOKEN" \
    -v "$WORKSPACE":/mnt/ \
    -v /etc/pki/tls/private/client.key:/etc/pki/tls/private/client.key \
    -v /etc/pki/tls/certs/client.crt:/etc/pki/tls/certs/client.crt \
    -v /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt \
    registry.ci.rmp.api.bbci.co.uk/programmes-docker-base "$@"
}

set -e

branch=$(echo $GIT_BRANCH | cut -d/ -f 2)
echo $JOB_NAME:$branch $WORKSPACE

rm -rf SRPMS

echo "Stopping existing Container..."
docker stop registry.ci.rmp.api.bbci.co.uk/programmes-docker-base || true

echo "Running CI in container..."
docker_run script/ci-docker

if [ "$BUILD_TYPE" = "pull-request" ]
then
    echo "Running mbt..."
	BUILD_COMMAND="mbt"
else
    echo "Running cosmos-build..."
	BUILD_COMMAND="cosmos-build"
fi
$BUILD_COMMAND -s docker -i registry.ci.rmp.api.bbci.co.uk/programmes-docker-base

echo "Stopping container..."
docker stop registry.ci.rmp.api.bbci.co.uk/programmes-docker-base || true
